coverage:
  status:
    project:
      default:
        target: 80%
        threshold: 1%
    patch:
      default:
        target: 70%

ignore:
  - "lib/**/*.g.dart"
  - "lib/**/*.freezed.dart"
  - "lib/**/*.mocks.dart"
  - "test/**"

comment:
  layout: "reach,diff,flags,components"
  behavior: default
  require_changes: true