site_name: Health Without Borders - Frontend Docs
site_description: Cross-platform frontend documentation for Health Without Borders.
site_url: https://guanes.github.io/health-without-borders-frontend/
repo_url: https://github.com/guanes/health-without-borders-frontend
repo_name: guanes/health-without-borders-frontend

theme:
  name: material

markdown_extensions:
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences

nav:
  - Home: index.md
  - Development:
    - Setup: development/setup.md
    - QA & PR Workflow: development/qa-plan.md
    - Figma to Flutter: development/figma-to-flutter.md
